#name: nyc_airbnb_dev
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  - python=3.10
#  - hydra-core=1.3.2
#  - matplotlib=3.8.2
#  - pandas=2.1.3
#  - jupyterlab=4.0.9
#  - pip=23.3.1
#  - pip:
#      - mlflow==2.8.1
#      - wandb==0.16.0


name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - hydra-core==1.3.2
      - matplotlib==3.8.2
      - pandas==2.1.3
      - jupyterlab==4.0.9
