#name: test_regression_model
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  - python=3.10.0
#  - pip=23.3.1
#  - requests=2.24.0
#  - scikit-learn=1.3.2
#  - pandas=2.1.3
#  - pip:
#      - mlflow==2.8.1
#      - wandb==0.16.0
#      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components


name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.2.2     # ✅ available and stable
  - pandas=2.2.1           # ✅ available and stable
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
