#name: basic_cleaning
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  - pandas=1.2.3
#  - pip=23.3.1
#  - python=3.10
#  - pip:
#      - mlflow==2.8.1
#      - wandb==0.16.0


name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3         # ✅ Compatible with Python 3.10
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
